name: Physicalfix 24 Hr Gym
favicon: null
layout_spectrum: 0.48403
typography_spectrum: 0.32408
title: Physical Fix 24 Hr Gym
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#000000'
    - '#535353'
    - '#a5a5a5'
    - '#232323'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
