name: Physicalfix
favicon: null
layout_spectrum: 0.74291
typography_spectrum: 0.32408
title: Physical Fix 24 Hr Gym
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#54c4dc'
    - '#ed008c'
    - '#fef200'
    - '#f259b4'
  brandStrength: 0
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
