name: Physicalfix
favicon: null
layout_spectrum: 0
typography_spectrum: 0.50483
title: Physical Fix 24 Hr Gym
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#54c4dc'
    - '#ed008c'
    - '#fef200'
    - '#f259b4'
  brandStrength: 0.875
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
